### ISSUE TITLE
Linter does not give warnings on missing JSDoc blocks

### ISSUE THREAD

**Issue by dwaard** [HZ-HBO-ICT/ts-skeleton-app#13]
SUGGESTED SOLUTION:
- Add `"eslint-plugin-jsdoc": "^37.0.3",` to devDependencies, or just install `npm install --save-dev eslint-plugin-jsdoc`
- Add `'plugin:jsdoc/recommended'` to eslintrc extends

**Comment by Lucky-Loek** [comment]
Klopt, omdat in de criteria juist Airbnb styleguide genoemd wordt en sinds niet al te lang hebben ze daar de dunctie comments uitgehaald. Dus of criteria aanpassen, of hiermee dealen 😅

**Comment by dwaard** [comment]
We hebben afgelopen PB toets wel puntaftrek gegeven als functions geen docblock hadden, totdat een student ons er idd op wees dat dit niet in airbnb staat. Ik denk wel dat we dit willen

**Comment by Lucky-Loek** [comment]
Ik denk het ook, maar dan moeten de criteria aangepast haha. Voeg maar toe, kan geen kwaad.
Gaat ie dan ook checken bij private methods? Want dat is wel vrij overdreven vind ik

**Comment by dwaard** [comment]
Done
