### ISSUE TITLE
Compiled files in repository

### ISSUE THREAD

**Issue by FrontEndCoffee** [HZ-HBO-ICT/ts-skeleton-app#2]
Usually it is not a good idea to have compiled files in your git-repository. There are files in the `output` folder.

I would suggest a few things:

* Rename `output` to `build` (or `dist` if you'd like). This would be more consistent with other JS and TS projects.

* Add the build folder to the `.gitignore`

* Remove the build files from the repo: `git rm --cached ./output`

If @Lucky-Loek is on board with this proposal I would be happy to draw up a PR!

**Comment by FrontEndCoffee** [comment]
@Lucky-Loek I completely understand. I have one more thing though: you have chosen npm as package manager. This is of course great, as it is the default tool for managing node dependencies. However, `yarn` is a great alternative. Yarn was introduced by Facebook and Google as an alternative for the sloppy/slow/crappy npm client. It uses the same package repo (npmjs.com) but it is far superior. -> [yarnpkg.com](https://yarnpkg.com)

I understand that you do not want to make it too complicated for the freshman year students, but I would really advise against using the default `npm` client.

**Comment by Lucky-Loek** [comment]
We only use NPM to install TypeScript, per the official docs. Is this the same procedure with Yarn? As in `yarn add -g typescript`? Cause I like Yarn a lot better too, but I see a couple of issues that Yarn and a global TS installation don't play well together.

**Comment by FrontEndCoffee** [comment]
I would use yarn, and avoid installing typescript globally all together (see https://github.com/HZ-HBO-ICT/ts-skeleton-app/issues/4)
