### ISSUE TITLE
Package manager

### ISSUE THREAD

**Issue by FrontEndCoffee** [HZ-HBO-ICT/ts-skeleton-app#4]
The project uses typescript to build its files. This is great, but in the readme it is recommended that contributors install typescript globally on their system.

This is a bad practice since the contributor might have two typescript projects on their system with conflicting versions of typescript! 

Of course this also bloats the contributor's system. It is generally a bad practice.

### Proposed fix:

Using NPM or Yarn, add a `package.json` that requires [typescript](https://www.npmjs.com/package/typescript) as a dev dependency. This way, the contributor can clone the repo, run `yarn install` or `npm install`, and run `npm build` or `yarn build` which triggers the build script defined in the `package.json`.

**Comment by Lucky-Loek** [comment]
The `yarn run build` or `npm run build` makes this a go for me. Thanks!
